bib=paper
full=("The Journal of Physical Chemistry B" "International Journal of Thermophysics" "Physical Review E" "The Journal of Chemical Physics" "Molecular Physics" "Journal of Computational Science" "Journal of Chemical Theory and Computation" "Fluid Phase Equilibria" "Journal of Pharmaceutical Sciences" "Molecular Systems Design \\\& Engineering" "Journal of Research of the National Institute of Standards and Technology" "The Journal of Physical Chemistry C" "The Journal of Physical Chemistry A" "AIChE Journal" "Journal of Computational Physics" "ACM Transactions on Modeling and Computer Simulation" "Molecular Simulation" "Living Journal of Computational Molecular Science" "Journal of Computational Chemistry" "Source Code for Biology and Medicine" "Journal of Chemical Information and Modeling" "Frontiers in Physics" "Physical Review Letters" "Nucleic Acids Research" "The Journal of Physical Chemistry" "Journal of Molecular Graphics" "Faraday Discussions of the Chemical Society" "Proceedings of the National Academy of Sciences" "Chemistry – A European Journal" "Journal of Applied Crystallography" "Physica A: Statistical Mechanics and its Applications" "Molecular physics" "Journal of Physics: Condensed Matter" "Europhysics Letters" "Computer Physics Communications" "Journal of Computational and Graphical Statistics" "Journal of Theoretical and Computational Chemistry" "Journal of the Physical Society of Japan" "Physics Letters B" "Chemical Physics Letters" "The European Physical Journal E" "Physical Review A" "Journal of Statistical Physics" "Living journal of computational molecular science" "Chemical Science")
abbrev=("J. Phys. Chem. B" "Int. J. Thermophys." "Phys. Rev. E" "J. Chem. Phys." "Mol. Phys." "J. Comput. Sci." "J. Chem. Theory Comput." "Fluid Ph. Equilib." "J. Pharm. Sci." "Mol. Syst. Des. Eng." "J. Res. Natl. Inst. Stand. Technol." "J. Phys. Chem. C" "J. Phys. Chem. A" "AIChE J." "J. Comput. Phys." "ACM Trans. Model. Comput. Simul." "Mol. Simul." "Living J. Comput. Mol. Sci." "J. Comput. Chem." "Source Code Biol. Med." "J. Chem. Inf. Model." "Front. Phys." "Phys. Rev. Lett." "Nucleic Acids Res." "J. Phys. Chem." "J. Mol. Graph." "Faraday Discuss." "Proc. Natl. Acad. Sci. USA" "Chem. Eur. J." "J. Appl. Crystallogr." "Physica A" "Mol. Phys." "J. Condens. Matter Phys." "Europhys. Lett." "Comput. Phys. Commun." "J. Comput. Graph. Statist." "J Theor. Comput. Chem." "J. Phys. Soc. Jpn." "Phys. Lett. B" "Chem. Phys. Lett." "Eur. Phys. J. E." "Phys. Rev. A" "J. Stat. Phys." "Living J. Comput. Mol. Sci." "Chem. Sci.")

for ((i = 0; i < ${#full[@]}; ++i)); do
#for ar in "${array}"; do
  echo "$i, ${full[i]} -> ${abbrev[i]}"
  sed -i "s/${full[i]}/${abbrev[i]}/g" $bib.bib
done
